/*
 * Outreach — AI-powered personalized email outreach
 * Design: "Warm Precision" — Scandinavian editorial, warm tones
 */
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { trpc } from "@/lib/trpc";
import {
  Send,
  Sparkles,
  Loader2,
  Mail,
  Copy,
  CheckCircle,
  Clock,
  Eye,
  MessageSquare,
  FileText,
  Pencil,
} from "lucide-react";
import { motion } from "framer-motion";
import { toast } from "sonner";

const fadeUp = {
  hidden: { opacity: 0, y: 16 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.4 } },
};

const stagger = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.08 } },
};

export default function Outreach() {
  const [leadName, setLeadName] = useState("");
  const [leadEmail, setLeadEmail] = useState("");
  const [company, setCompany] = useState("");
  const [tone, setTone] = useState<"professional" | "friendly" | "urgent" | "casual">("professional");
  const [context, setContext] = useState("");
  const [generatedEmail, setGeneratedEmail] = useState<{
    subject: string;
    body: string;
    followUpSuggestion: string;
  } | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [editSubject, setEditSubject] = useState("");
  const [editBody, setEditBody] = useState("");

  // Queries
  const { data: campaigns, isLoading: campaignsLoading, refetch: refetchCampaigns } = trpc.outreach.list.useQuery({ limit: 50 });
  const { data: outreachStats } = trpc.outreach.stats.useQuery();
  const { data: allLeads } = trpc.leads.list.useQuery({ limit: 100 });

  // Mutations
  const generateEmail = trpc.outreach.generateEmail.useMutation({
    onSuccess: (data) => {
      setGeneratedEmail(data);
      setEditSubject(data.subject);
      setEditBody(data.body);
      toast.success("Email generated by AI");
    },
    onError: (err) => {
      toast.error(`Generation failed: ${err.message}`);
    },
  });

  const createCampaign = trpc.outreach.create.useMutation({
    onSuccess: () => {
      toast.success("Outreach campaign saved");
      refetchCampaigns();
      setGeneratedEmail(null);
      setLeadName("");
      setLeadEmail("");
      setCompany("");
      setContext("");
    },
    onError: (err) => {
      toast.error(`Failed to save: ${err.message}`);
    },
  });

  const markSent = trpc.outreach.markSent.useMutation({
    onSuccess: () => {
      toast.success("Marked as sent");
      refetchCampaigns();
    },
  });

  const handleGenerate = () => {
    if (!leadName || !leadEmail || !company) {
      toast.error("Please fill in name, email, and company");
      return;
    }
    generateEmail.mutate({
      leadName,
      leadEmail,
      company,
      tone,
      context: context || undefined,
    });
  };

  const handleSaveCampaign = () => {
    if (!editSubject || !editBody) {
      toast.error("Subject and body are required");
      return;
    }
    createCampaign.mutate({
      leadName,
      leadEmail,
      subject: editSubject,
      body: editBody,
      tone,
      generatedByAi: true,
    });
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success("Copied to clipboard");
  };

  const getStatusBadge = (status: string) => {
    const colors: Record<string, string> = {
      draft: "bg-slate-100 text-slate-700",
      sent: "bg-blue-100 text-blue-700",
      opened: "bg-amber-100 text-amber-700",
      replied: "bg-green-100 text-green-700",
      bounced: "bg-red-100 text-red-700",
    };
    return colors[status] ?? colors.draft;
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "draft": return FileText;
      case "sent": return Send;
      case "opened": return Eye;
      case "replied": return MessageSquare;
      default: return Clock;
    }
  };

  return (
    <motion.div initial="hidden" animate="visible" variants={stagger} className="space-y-6">
      {/* Header */}
      <motion.div variants={fadeUp}>
        <h1 className="text-2xl font-display text-foreground">Automated Outreach</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Generate personalized outreach emails using AI and manage campaigns
        </p>
      </motion.div>

      {/* Stats */}
      <motion.div variants={fadeUp} className="grid grid-cols-2 md:grid-cols-5 gap-3">
        {[
          { label: "Total", value: outreachStats?.total ?? 0, icon: Mail },
          { label: "Drafts", value: outreachStats?.draft ?? 0, icon: FileText },
          { label: "Sent", value: outreachStats?.sent ?? 0, icon: Send },
          { label: "Opened", value: outreachStats?.opened ?? 0, icon: Eye },
          { label: "Replied", value: outreachStats?.replied ?? 0, icon: MessageSquare },
        ].map((stat) => (
          <Card key={stat.label} className="border border-border/40">
            <CardContent className="p-3 flex items-center gap-2">
              <stat.icon className="w-4 h-4 text-terracotta" />
              <div>
                <p className="text-lg font-semibold tabular-nums text-foreground">{stat.value}</p>
                <p className="text-[10px] text-muted-foreground">{stat.label}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
        {/* Email Generator */}
        <motion.div variants={fadeUp} className="lg:col-span-2">
          <Card className="border border-border/40">
            <CardHeader className="pb-3">
              <CardTitle className="font-display text-lg flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-terracotta" />
                Generate Email
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {/* Quick select from existing leads */}
              {allLeads && allLeads.length > 0 && (
                <div>
                  <label className="text-xs font-medium text-muted-foreground mb-1 block">Quick Select Lead</label>
                  <Select
                    onValueChange={(v) => {
                      const lead = allLeads.find(l => l.id.toString() === v);
                      if (lead) {
                        setLeadName(lead.name);
                        setLeadEmail(lead.email);
                        setCompany(lead.company);
                      }
                    }}
                  >
                    <SelectTrigger className="text-sm">
                      <SelectValue placeholder="Select a lead..." />
                    </SelectTrigger>
                    <SelectContent>
                      {allLeads.map((lead) => (
                        <SelectItem key={lead.id} value={lead.id.toString()} className="text-sm">
                          {lead.name} — {lead.company}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              )}

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="text-xs font-medium text-muted-foreground mb-1 block">Name *</label>
                  <Input value={leadName} onChange={(e) => setLeadName(e.target.value)} placeholder="Sarah Chen" className="text-sm" />
                </div>
                <div>
                  <label className="text-xs font-medium text-muted-foreground mb-1 block">Email *</label>
                  <Input value={leadEmail} onChange={(e) => setLeadEmail(e.target.value)} placeholder="sarah@co.com" className="text-sm" />
                </div>
              </div>

              <div>
                <label className="text-xs font-medium text-muted-foreground mb-1 block">Company *</label>
                <Input value={company} onChange={(e) => setCompany(e.target.value)} placeholder="Acme Corp" className="text-sm" />
              </div>

              <div>
                <label className="text-xs font-medium text-muted-foreground mb-1 block">Tone</label>
                <Select value={tone} onValueChange={(v: typeof tone) => setTone(v)}>
                  <SelectTrigger className="text-sm">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="professional">Professional</SelectItem>
                    <SelectItem value="friendly">Friendly</SelectItem>
                    <SelectItem value="urgent">Urgent</SelectItem>
                    <SelectItem value="casual">Casual</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <label className="text-xs font-medium text-muted-foreground mb-1 block">Context</label>
                <Textarea
                  value={context}
                  onChange={(e) => setContext(e.target.value)}
                  placeholder="They visited pricing page 3 times this week..."
                  className="text-sm h-16 resize-none"
                />
              </div>

              <Button
                onClick={handleGenerate}
                disabled={generateEmail.isPending}
                className="w-full bg-terracotta hover:bg-terracotta/90 text-white"
              >
                {generateEmail.isPending ? (
                  <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating...</>
                ) : (
                  <><Sparkles className="w-4 h-4 mr-2" /> Generate with AI</>
                )}
              </Button>

              {/* Generated Email Preview */}
              {generatedEmail && (
                <div className="mt-4 space-y-3 p-4 rounded-lg bg-muted/30 border border-border/20">
                  <div className="flex items-center justify-between">
                    <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Generated Email</h4>
                    <div className="flex gap-1">
                      <Button variant="ghost" size="sm" className="h-7 text-xs" onClick={() => copyToClipboard(`Subject: ${editSubject}\n\n${editBody}`)}>
                        <Copy className="w-3 h-3 mr-1" /> Copy
                      </Button>
                    </div>
                  </div>
                  <div>
                    <label className="text-[10px] text-muted-foreground">Subject</label>
                    <Input value={editSubject} onChange={(e) => setEditSubject(e.target.value)} className="text-sm mt-1" />
                  </div>
                  <div>
                    <label className="text-[10px] text-muted-foreground">Body</label>
                    <Textarea value={editBody} onChange={(e) => setEditBody(e.target.value)} className="text-sm mt-1 h-32" />
                  </div>
                  <p className="text-xs text-muted-foreground italic">
                    Follow-up: {generatedEmail.followUpSuggestion}
                  </p>
                  <Button
                    onClick={handleSaveCampaign}
                    disabled={createCampaign.isPending}
                    className="w-full"
                    variant="outline"
                  >
                    {createCampaign.isPending ? (
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    ) : (
                      <CheckCircle className="w-4 h-4 mr-2" />
                    )}
                    Save Campaign
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>
        </motion.div>

        {/* Campaign List */}
        <motion.div variants={fadeUp} className="lg:col-span-3">
          <Card className="border border-border/40">
            <CardHeader className="pb-3">
              <CardTitle className="font-display text-lg flex items-center gap-2">
                <Mail className="w-5 h-5 text-terracotta" />
                Campaigns
              </CardTitle>
            </CardHeader>
            <CardContent>
              {campaignsLoading ? (
                <div className="flex items-center justify-center py-12">
                  <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
                </div>
              ) : !campaigns?.length ? (
                <div className="text-center py-12">
                  <Send className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
                  <p className="text-sm text-muted-foreground">No campaigns yet</p>
                  <p className="text-xs text-muted-foreground/60 mt-1">Generate your first AI-powered outreach email</p>
                </div>
              ) : (
                <div className="space-y-2 max-h-[600px] overflow-y-auto">
                  {campaigns.map((campaign) => {
                    const StatusIcon = getStatusIcon(campaign.status);
                    return (
                      <div
                        key={campaign.id}
                        className="p-3 rounded-lg bg-muted/20 border border-border/20 hover:border-border/40 transition-all"
                      >
                        <div className="flex items-start justify-between mb-2">
                          <div className="flex-1">
                            <p className="text-sm font-medium text-foreground truncate">{campaign.subject}</p>
                            <p className="text-xs text-muted-foreground">
                              To: {campaign.leadName} ({campaign.leadEmail})
                            </p>
                          </div>
                          <div className="flex items-center gap-2">
                            <Badge className={`text-[10px] ${getStatusBadge(campaign.status)}`}>
                              <StatusIcon className="w-3 h-3 mr-1" />
                              {campaign.status}
                            </Badge>
                            {campaign.generatedByAi && (
                              <Badge className="text-[10px] bg-purple-100 text-purple-700">
                                <Sparkles className="w-3 h-3 mr-1" /> AI
                              </Badge>
                            )}
                          </div>
                        </div>
                        <p className="text-xs text-muted-foreground line-clamp-2">{campaign.body}</p>
                        <div className="flex items-center gap-2 mt-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-6 text-[10px]"
                            onClick={() => {
                              setEditSubject(campaign.subject);
                              setEditBody(campaign.body);
                              setShowPreview(true);
                            }}
                          >
                            <Eye className="w-3 h-3 mr-1" /> Preview
                          </Button>
                          {campaign.status === "draft" && (
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-6 text-[10px] text-terracotta"
                              onClick={() => markSent.mutate({ id: campaign.id })}
                            >
                              <Send className="w-3 h-3 mr-1" /> Mark Sent
                            </Button>
                          )}
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-6 text-[10px]"
                            onClick={() => copyToClipboard(`Subject: ${campaign.subject}\n\n${campaign.body}`)}
                          >
                            <Copy className="w-3 h-3 mr-1" /> Copy
                          </Button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </CardContent>
          </Card>
        </motion.div>
      </div>

      {/* Preview Dialog */}
      <Dialog open={showPreview} onOpenChange={setShowPreview}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="font-display">Email Preview</DialogTitle>
          </DialogHeader>
          <div className="space-y-3">
            <div className="p-3 rounded-lg bg-muted/20">
              <p className="text-xs text-muted-foreground mb-1">Subject</p>
              <p className="text-sm font-medium text-foreground">{editSubject}</p>
            </div>
            <div className="p-3 rounded-lg bg-muted/20">
              <p className="text-xs text-muted-foreground mb-1">Body</p>
              <p className="text-sm text-foreground whitespace-pre-wrap">{editBody}</p>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </motion.div>
  );
}
